# Specify base image
FROM node:18.17.0

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json before other files
# Utilise Docker cache to save re-installing dependencies if unchanged
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY ./ ./

# Build application
RUN npm run build

# Specify the command to run
CMD [ "npm", "start" ]

# Expose the port the app runs on
EXPOSE 3000
